.\" Process this file with
.\" groff -man -Tascii foo.1
.\"

.TH taskManager 1 "NOV 2010" Linux/Unix "User Manuals"

.SH NAME
taskManager \- a command line based to-do list manager

.SH SYNOPSIS
.B taskManager [
.I subcommand1
.B ] | [
.I subcommand2 
.B ] | ...

.SH DESCRIPTION
.B TaskManager 
is a console todo list utility. It maintains a list of tasks and provides a rich collection of commands to manipulate as well as browse them. It comes with a TaskManager shell and an interactive text-based user interface (TUI); supports command aliasing, piping and start up script. A decent set of command aliases are defined in the default \fI.tmrc\fP file to enable intuitive command line task management, an auto-completion module adds on to the usability while import and export commands make sharing and visualizing tasks easy. 

For more information, check \fIUserguide.pdf\fP.

.SH SUBCOMMANDS

.TP
.B add \fIdescription\fP [ -g \fIgroup \fB] [ -t \fItime \fB] [ -p \fIpriority \fB]
Add a new task to the task list.

\fB-g \fPSpecify a group for the task. Typically it is a string of length less than 10.

\fB-t \fPSpecify a deadline for the task. Time format is discussed in later session. If tasks are added with no \fB-t \fPoption, their deadline appears to be \fB Anytime\fP.

\fB-p \fPSpecify a priority for the task. Typically it is a number between -20 and 20.

.TP
\fBls [ -s "\fI Keyword1\fP \fIKeyword2\fP ...\fB" ] [ -k \fIKeyword\fB ] [ -f \fIyes/no\fB ] [ -g \fIgroup\fB ] [ -i \fIt0\fB:\fIt1\fB ]\fP
Provide a list of added tasks. 

\fB-s \fPSort the list with Keyword(s) specified. Available keywords are \fBdeadline\fP, \fBpriority\fP, \fBserialnumber\fP.

\fB-k \fPFilter the list with keyword provided. Keywords can contain \fB*\fP and \fB?\fP.

\fB-g \fPShow only tasks from specific group.

\fB-i \fPShow a list of tasks with deadline between t0 and t1. (>=t0, <t1)

.TP
.B rm [ \fItaskNumber1\fP \fItaskNumber2\fP \fItaskNumber2\fP \fB... ] [ -g \fIgroup\fB ]
Remove the tasks with provided searial numbers. 

\fB-g \fPRemove all tasks from a specific group.

.TP
\fBedit \fIserialNumber\fB [ -d "\fIdescription\fB" ] [ -g \fIgroup \fB] [ -t \fItime \fB] [ -p \fIpriority \fB] [ -f \fIyes/no\fB ]\fP
Edit the task with specific task number.

\fB-d \fPSpecify a new description for the task.

\fB-g \fPSpecify a new group for the task.

\fB-t \fPSpecify a new deadline for the task. 

\fB-p \fPSpecify a new priority for the task. 

\fB-f \fPSpecify whether the task is finished.

.TP
.B finish \fIserialNumber\fP
Mark a task as finished.

.TP
.B read \fIfilename\fP
Read tasks from a XML file which by default is ~/record.xml, list all the tasks it contains without affacting current task list.

.TP 
.B import \fIfilename\fP
Read the content of the XML file and appends all the tasks in it to current task list

.TP
.B export [ -html ] \fIfilename\fP
Export current task list to a XML file which by default is ~/record.xml. If \fB-html\fP option is specified, it exports to a well formatted HTML webpage.

.TP
.B task \fIserialNumber\fP
Inspect the detail of a task

.TP
.B pri \fIserialNumber\fB [ \fIpriority\fB ]\fP
Modify priority of of a task. If new priority is not specified, the priority is set to 20. 

.TP
.B undo
Undo last command. These commands cannot be undo: \fBls\fp, \fBexport\fP, \fBundo\fP, \fBredo\fP, \fBtui\fP, \fBnotui\fP, \fBread\fP, \fBtask\fP.

.TP
.B redo
Redo last undo command. It can be executed until all undos are re-done.

.TP
.B tui
Start a text based interactive user interface.

.TP
.B notui
Stop the interactive user interface and back to command line user interface.

.TP
\fBmap "\fIcustomized command\fB" "\fIoriginal command\fB"
Map a existing command to a customized command. $0 and $1,2,3,4... can be used as variable to replace token. Please refer to user guide for more details. Adding \fB\\\fP before a command suppress this functionality.

.TP
.B run \fIfilename\fP
Run a taskManager script.

.TP
.B exit
Exit taskManager

.SH TIME FORMAT
TaskManager support 3 time formats: \fB"plus" format\fP, \fB"by" format\fP, \fBunix timestamp\fP.

.TP
\fB "plus" format
Plus format specifies the amount of time from now.

\fB?w?d?h?m \fPEach question mark stands for a number. E.g. \fB3d2h\fP means 3 days and 2 hours later.

.TP
\fB "by" format
By format specifies the amount of time from the start of this hour/day/week.

\fBb?w?d?h?m \fPEach question mark stands for a number. Examples are show below:

\fBb0d22h  \fPby 10:00pm today.

\fBb2d     \fPby 23:59 tomorrow.

\fBb1w     \fPby the end of this week. i.e. 23:59 of the Saturday11of this week.

\fBb0w5d   \fPby 23:59 on Friday of this week.

\fBb2w3d8h \fPby 8:00am on the Wednesday of the next next week.

.TP
.B UNIX timestamp
A number specify the number of seconds from 00:00 1/1/1970 UTC.

.SH ALIASED COMMANDS
A number of command mapping is given in the sample tmrc file to enable more intuitive commandline task management.

.TP
\fBAdding task\fP
A task can be added using one of the following four way.

\fBa [ for \fP\fIgroup\fP\fB ] \fP\fIdescription\fP 

Add a task that can be done at anytime

\fBimportant [ for \fP\fIgroup\fP\fB ] \fP\fIdescription\fP

Add a task with priority to be 20

\fB[ today/tomorrow ] [ \fP\fItime\fP\fB ] [ for \fP\fIgroup\fP\fB ] \fP\fIdescription\fP

Add a task dues on today or tomorrow. If no today or tomorrow specified, the task is added with due day to be today.

\fBtime\fP can be 8am ~ 11am, noon or 1pm ~ 8pm. 

At least one of time and today/tomorrow must be specified.

\fB[ next ] \fP\fIweekday\fP\fB [ \fP\fItime\fP\fB ][ for \fP\fIgroup\fP\fB ] \fP\fIdescription\fP

Add a task dues on a specific week day. 
\fBweekday\fP can be \fBSunday, Monday, Tuesday, Wednesday, Thursday, Friday \fPor \fBSaturday.\fP

.TP
.B Browsering task

\fBall \fP\fIgroup\fP

List all tasks from a specific group

\fBwhat \fP\fIgroup\fP

List all unfinished tasks from a specific group

\fBwhat [ can i do ] today\fP

List all unfinished tasks which due on today or tomorrow

\fBwhat [ can i do ] tomorrow\fP

List all unfinished tasks which due on tomorrow or the day after tomorrow

\fBwhat [ can i do ] this week\fP

List all unfinished tasks which due in this week

\fBwhat [ can i do ] next week\fP

List all unfinished tasks which due in next week

.SH FILES

.TP 
.I ~/record.xml
Current task list is stored here by default.

.TP 
.I ~/.tmrc
The start up script executed by taskManager before it starts.

.SH AUTHOR
Liu Jialong, Zhou Biyan, Wang Xiangyu, He Haocong

