.\" Process this file with
.\" groff -man -Tascii foo.1
.\"

.TH taskManager 1 "SEP 2010" Linux/Unix "User Manuals"
.SH NAME
taskManager \- a command line based to-do list manager
.SH SYNOPSIS
.B taskManager [ -c
.I config-file
.B ] [ -g ] [ -i
.I xml-file
.B ]
.SH DESCRIPTION
.B taskManager
provides a blah blah blah blah which enables blah blah blah
It manages blah blah blah.
.SH OPTIONS
.IP "-c config-file"
Use the 
.I config-file
instead of 
.IR /etc/taskManager.conf
.IP -g
Start taskManager with a text based GUI
.IP "-i xml-file"
Import 
.I xml-file
when starting taskManager
.SH FILES
.I /etc/taskManager.conf
.RS
The system wide configuration file.
.I ~/.taskManagerrc
Per user configuration file.
.SH AUTHOR
Liu Jialong, Zhou Biyan, Wang Xiangyu, He Haocong

